package lotto;

import lotto.domain.BonusNumber;
import lotto.domain.Lotto;
import lotto.domain.Lottos;
import lotto.domain.Money;
import lotto.domain.Stats;
import lotto.view.InputView;
import lotto.view.OutputView;

public class Application {

    public static void main(String[] args) {
        try {
            run();
        } catch (Exception e) {
            // exit
        }
    }

    private static void run() {
        Money money = new Money(InputView.askAmount());
        Lottos autoGeneratedLottos = LottoMachine.issueLottos(money);
        OutputView.printLottos(autoGeneratedLottos);

        Lotto winningLotto = new Lotto(InputView.askWinningNumber());
        BonusNumber bonusNumber = new BonusNumber(winningLotto, InputView.askBonusNumber());

        Stats stats = new Stats();
        stats.produceLottoResult(autoGeneratedLottos, winningLotto, bonusNumber);
        stats.produceRateOfProfit(money);
        OutputView.printLottoResult(stats);
        OutputView.printRateOfProfit(stats);
    }
}
