package lotto.domain;

public class Stats {

    private final LottoResult lottoResult;
    private double rateOfProfit;

    public Stats() {
        lottoResult = new LottoResult();
    }

    public void produceLottoResult(Lottos autoGeneratedLottos, Lotto winningLotto, BonusNumber bonusNumber) {
        autoGeneratedLottos.rank(lottoResult, winningLotto, bonusNumber);
    }

    public void produceRateOfProfit(Money money) {
        long profit = lottoResult.calculateProfits();
        long amount = money.getMoney();

        if (amount == 0) {
            rateOfProfit = 0;
            return;
        }
        rateOfProfit = (double) profit / amount * 100;
    }

    public double getRateOfProfit() {
        return rateOfProfit;
    }

    public LottoResult getLottoResult() {
        return lottoResult;
    }
}
