package lotto.restrict;

public interface RestrictConstants {

	int LIMIT_SIZE = 6;
	int MIN_NUMBER = 1;
	int MAX_NUMBER = 45;
	int AMOUNT_UNIT = 1000;
	int BONUS_QUANTITY = 1;

	int SECOND_RANK_BONUS_CONDITION = 1;
	int FIRST_RANK_CONDITION = 6;
	int SECOND_RANK_CONDITION = 5;
	int THIRD_RANK_CONDITION = 5;
	int FOURTH_RANK_CONDITION = 4;
	int FIFTH_RANK_CONDITION = 3;

	int FIRST_RANK_COMPENSATION = 2000000000;
	int SECOND_RANK_COMPENSATION = 30000000;
	int THIRD_RANK_COMPENSATION = 1500000;
	int FOURTH_RANK_COMPENSATION = 50000;
	int FIFTH_RANK_COMPENSATION = 5000;

	String DELIMITER = ",";
}
