package lotto;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

import java.util.ArrayList;
import java.util.List;
import lotto.domain.LottoIssueMachine;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class LottoIssueMachineTest {
    private static LottoIssueMachine lottoIssueMachine;

    @BeforeAll
    static void initMachine() {
        lottoIssueMachine = new LottoIssueMachine();
    }

    @Test
    @DisplayName("자동으로 로또번호를 생성힌다.")
    void autoGeneratedLotto() {
        assertThat(lottoIssueMachine.autoGenerate().getNumbers()).isNotNull();
    }

    @Test
    @DisplayName("수동으로 로또번호를 생성한다.")
    void manualGeneratedLotto() {
        List<Integer> given = new ArrayList<>(List.of(1, 2, 3, 4, 5, 6));
        List<Integer> expected = new ArrayList<>(List.of(1, 2, 3, 4, 5, 6));
        assertThat(lottoIssueMachine.manualGenerate(given).getNumbers()).isEqualTo(expected);
    }
}