package lotto;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class LottoMachineTest {
    private static LottoMachine lottoMachine;
    @BeforeAll
    static void initMachine(){
        lottoMachine = new LottoMachine();
    }

    @Test
    void autoGeneratedLotto() {
        assertThat(lottoMachine.autoGenerate().getNumbers()).isNotNull();
    }

    @Test
    void manualGeneratedLotto() {
        List<Integer> given = new ArrayList<>(List.of(1, 2, 3, 4, 5, 6));
        List<Integer> expected = new ArrayList<>(List.of(1, 2, 3, 4, 5, 6));
        assertThat(lottoMachine.manualGenerate(given).getNumbers()).isEqualTo(expected);
    }
}